# Generated by Django 5.1.5 on 2025-02-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('camera', models.CharField(max_length=100)),
                ('incident_type', models.CharField(max_length=200)),
            ],
        ),
    ]
